// File generated by FlutterFire CLI.
// ignore_for_file: type=lint, lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAItIvovjZo80G_d4uDLfbR4e_F6BsNSns',
    appId: '1:590805636916:web:6f7c2a8408dc4016fc3761',
    messagingSenderId: '590805636916',
    projectId: 'fripesfinderv2',
    authDomain: 'fripesfinderv2.firebaseapp.com',
    storageBucket: 'fripesfinderv2.firebasestorage.app',
    measurementId: 'G-5Y6F5W7TZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs8aWf1PWZ6ZL3uBuz4NRm-tIPa4rEQMg',
    appId: '1:590805636916:android:6c6a8a96d125f6acfc3761',
    messagingSenderId: '590805636916',
    projectId: 'fripesfinderv2',
    storageBucket: 'fripesfinderv2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUXd_1zRIgHHeHTXG6nXg1kwrYXES-1_Y',
    appId: '1:590805636916:ios:e90fef0634d9414ffc3761',
    messagingSenderId: '590805636916',
    projectId: 'fripesfinderv2',
    storageBucket: 'fripesfinderv2.firebasestorage.app',
    iosBundleId: 'com.example.fripesfinderv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUXd_1zRIgHHeHTXG6nXg1kwrYXES-1_Y',
    appId: '1:590805636916:ios:e90fef0634d9414ffc3761',
    messagingSenderId: '590805636916',
    projectId: 'fripesfinderv2',
    storageBucket: 'fripesfinderv2.firebasestorage.app',
    iosBundleId: 'com.example.fripesfinderv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAItIvovjZo80G_d4uDLfbR4e_F6BsNSns',
    appId: '1:590805636916:web:65c9a7e3cd7fceeffc3761',
    messagingSenderId: '590805636916',
    projectId: 'fripesfinderv2',
    authDomain: 'fripesfinderv2.firebaseapp.com',
    storageBucket: 'fripesfinderv2.firebasestorage.app',
    measurementId: 'G-B7YWM419Q1',
  );

}